### ISSUE TITLE
Game crash when generating structure

### ISSUE THREAD

**Issue by CharlesBuckington** [Binaris00/Fabric_Potions#2]
When generating a jungle temple from repurposed structures with this mod installed the game crashes with the following, pretty short, log.
I was able to replicate this by locating jungle temples and getting close to them. It happens at about every second temple.

[13:32:32] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_1667 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_1667 and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1ce92674)
	**at net.minecraft.class_1309.handler$cpi000$fabric-potions$moreDamage(class_1309.java:17680) ~[client-intermediary.jar:?]**
	at net.minecraft.class_1309.method_6036(class_1309.java:1676) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6074(class_1309.java:1684) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1163) ~[client-intermediary.jar:?]
	at net.minecraft.class_1665.method_7454(class_1665.java:374) ~[client-intermediary.jar:?]
	at net.minecraft.class_1676.method_7488(class_1676.java:153) ~[client-intermediary.jar:?]
	at net.minecraft.class_1665.method_5773(class_1665.java:227) ~[client-intermediary.jar:?]
	at net.minecraft.class_1667.method_5773(class_1667.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	... 5 more

**Comment by CharlesBuckington** [comment]
It appears to also happen with any other structure that uses dispenser traps that shoot potions

**Comment by Binaris00** [comment]
What version of the mod are you using?, I can't reply the error in the 1.20.2.

**Comment by CharlesBuckington** [comment]
I am currently using [fabric-potions-1.0.0] for 1.20.1. 
I will try to replicate the crash in 1.20.2 myself.

**Comment by shallow-zzt** [comment]
The same issue occured with mod version [fabric-potions-1.0.0] for 1.20.1
You can consider make 1.1.0 version of the mod to 1.20.1 minecraft.

**Comment by shallow-zzt** [comment]
> I am currently using [fabric-potions-1.0.0] for 1.20.1. I will try to replicate the crash in 1.20.2 myself.

I found a possible way to solve this.
Download the mod for 1.20.2 mc.
Just open the .jar file and modify fabric.mod.json
Find the key "depends" and  modify the minecraft version to 1.20.1
`		
"minecraft": "~1.20.1"
`

The chash will be repaired and enjoy the minecraft!

**Comment by Binaris00** [comment]
I'll update the 1.20.1 to fix this, thanks for the report
